### ISSUE TITLE
Shuffle the hosts when connecting to the broker

### ISSUE THREAD

**Issue by k32** [emqx/emqttb#13]
Currently the first successful broker is used when multiple hosts are specified.

**Comment by thalesmg** [comment]
Perhaps the distribution of hosts could be somewhat configurable?

For example: to test only intra-broker publishing on a 1-1 topology (publishers and subscribers on the same node), each matching client would need to connect to the same node.  To force all messages to be forwarded inter-brokers, they'd have to be placed on different servers.

**Comment by ieQu1** [comment]
Fixed by #16
